# Problem 1 

In [1]:
# 1 - numpy kütüphanesini import edin
import numpy as np

# 2 - 5 elemanlı bir numpy array oluşturun
dizi = np.array([12, 5, 23, 7, 1])

# 3 - Oluşturduğunuz array'i küçükten büyüğe sıralayın
sirali_dizi = np.sort(dizi)

print("Sıralanmış dizi:", sirali_dizi)


Sıralanmış dizi: [ 1  5  7 12 23]


# Problem 2

In [2]:
import numpy as np

# 1
dizi1 = np.array([10, 15, 30, 45, 60])
print("1. Belirli değerlerden oluşan dizi:", dizi1)

# 2
dizi2 = np.arange(5, 16)
print("2. 5-15 arası sayılardan oluşan dizi:", dizi2)

# 3
dizi3 = np.arange(50, 101, 5)
print("3. 50-100 arası 5'er artan dizi:", dizi3)

# 4
dizi4 = np.zeros(10)
print("4. 10 elemanları sıfırlardan oluşan dizi:", dizi4)

# 5
dizi5 = np.ones(10)
print("5. 10 elemanları birlerden oluşan dizi:", dizi5)

# 6
dizi6 = np.linspace(0, 100, 5)
print("6. 0-100 arasında eşit aralıklı 5 sayı:", dizi6)

# 7
dizi7 = np.random.randint(10, 31, 5)
print("7. 10-30 arasında rastgele 5 tamsayı:", dizi7)

# 8
dizi8 = np.random.uniform(-1, 1, 10)
print("8. -1 ile 1 arasında rastgele 10 sayı:", dizi8)

# 9
matris = np.random.randint(10, 51, (3, 5))
print("9. 3x5 boyutunda 10-50 arasında rastgele matris:\n", matris)

# 10
print("10. Satır toplamları:", matris.sum(axis=1))
print("10. Sütun toplamları:", matris.sum(axis=0))

# 11
print("11. En büyük değer:", matris.max())
print("11. En küçük değer:", matris.min())
print("11. Ortalama:", matris.mean())

# 12
print("12. En büyük değerin indeksi:", np.unravel_index(matris.argmax(), matris.shape))

# 13
dizi9 = np.arange(10, 21)
print("13. 10-20 arasındaki dizinin ilk 3 elemanları:", dizi9[:3])

# 14
print("14. Dizinin ters hali:", dizi9[::-1])

# 15
print("15. Matrisin ilk satırı:", matris[0])

# 16
print("16. Matrisin 2. satır 3. sütundaki elemanları:", matris[1, 2])

# 17
print("17. Tüm satırların ilk elemanları:", matris[:, 0])

# 18
print("18. Matrisin tüm elemanlarının karesi:\n", matris ** 2)

# 19
matris2 = np.random.randint(-50, 51, (3, 5))
pozitif_ciftler = matris2[(matris2 > 0) & (matris2 % 2 == 0)]
print("19. (-50,+50) arasında matris:\n", matris2)
print("19. Pozitif çift sayılar:", pozitif_ciftler)


1. Belirli değerlerden oluşan dizi: [10 15 30 45 60]
2. 5-15 arası sayılardan oluşan dizi: [ 5  6  7  8  9 10 11 12 13 14 15]
3. 50-100 arası 5'er artan dizi: [ 50  55  60  65  70  75  80  85  90  95 100]
4. 10 elemanları sıfırlardan oluşan dizi: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
5. 10 elemanları birlerden oluşan dizi: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
6. 0-100 arasında eşit aralıklı 5 sayı: [  0.  25.  50.  75. 100.]
7. 10-30 arasında rastgele 5 tamsayı: [11 19 24 23 14]
8. -1 ile 1 arasında rastgele 10 sayı: [-0.1740389  -0.16893543  0.37186031  0.98044405 -0.99483913 -0.48856877
 -0.17932896  0.02833621 -0.85649623  0.79351627]
9. 3x5 boyutunda 10-50 arasında rastgele matris:
 [[14 45 36 28 23]
 [40 10 48 39 37]
 [15 47 47 47 11]]
10. Satır toplamları: [146 174 167]
10. Sütun toplamları: [ 69 102 131 114  71]
11. En büyük değer: 48
11. En küçük değer: 10
11. Ortalama: 32.46666666666667
12. En büyük değerin indeksi: (np.int64(1), np.int64(2))
13. 10-20 arasındaki dizinin ilk 3 elemanları