# Problem 1

In [7]:
# 1 - numpy kütüphanesini import edin
import numpy as np

# 2 - 0 ile 10 arasında 5 sayıdan oluşan matris üretin
matris = np.random.randint(0, 11, size=(5,))
print("Matris:", matris)

# 3 - matris'in boyutunu öğrenin
print("Matrisin Boyutu:", matris.shape)

# 4 - matris'i yeniden boyutlandırın
matris = matris.reshape((5, 1))
print("Yeniden Boyutlandırılmış Matris:\n", matris)

# 5 - matris'in boyut sayısını öğrenin
print("Matrisin Boyut Sayısı:", matris.ndim)


Matris: [6 6 1 7 9]
Matrisin Boyutu: (5,)
Yeniden Boyutlandırılmış Matris:
 [[6]
 [6]
 [1]
 [7]
 [9]]
Matrisin Boyut Sayısı: 2


# Problem 2

In [8]:
# 1 - 0 ile 10 arasında bulunan tek sayılardan oluşan matris üretin
tek_sayilar = np.arange(1, 11, 2)
matris2 = tek_sayilar.reshape((5, 1))
print("Tek Sayılardan Oluşan Matris:\n", matris2)

# 2 - Oluşturduğunuz matrisi parçalayıp ikiye bölün
parca1 = matris2[:2]
parca2 = matris2[2:]
print("Birinci Parça:\n", parca1)
print("İkinci Parça:\n", parca2)

# 3 - Parçalanmış matrisleri birleştirin
birlesmis = np.vstack((parca1, parca2))
print("Birleştirilmiş Matris:\n", birlesmis)


Tek Sayılardan Oluşan Matris:
 [[1]
 [3]
 [5]
 [7]
 [9]]
Birinci Parça:
 [[1]
 [3]]
İkinci Parça:
 [[5]
 [7]
 [9]]
Birleştirilmiş Matris:
 [[1]
 [3]
 [5]
 [7]
 [9]]


# Problem 3

In [9]:
# 1 - 5 ile 100 arasında ikişer ikişer atlayarak rastgele 10 sayıdan oluşan matris üretin
import numpy as np

sayilar = np.arange(5, 101, 2) 
matris3 = np.random.choice(sayilar, size=10, replace=False)
print("Oluşturulan Matris:\n", matris3)

# 2 - Matris'in özelliklerini inceleyin
print("Matrisin Şekli (shape):", matris3.shape)
print("Matrisin Boyut Sayısı (ndim):", matris3.ndim)
print("Matrisin Veri Tipi (dtype):", matris3.dtype)
print("Matrisin Toplam Eleman Sayısı (size):", matris3.size)
print("Matrisin En Küçük Elemanı:", matris3.min())
print("Matrisin En Büyük Elemanı:", matris3.max())
print("Matrisin Ortalaması:", matris3.mean())
print("Matrisin Standart Sapması:", matris3.std())


Oluşturulan Matris:
 [53 11 25 31 89 71 59 21 61 69]
Matrisin Şekli (shape): (10,)
Matrisin Boyut Sayısı (ndim): 1
Matrisin Veri Tipi (dtype): int64
Matrisin Toplam Eleman Sayısı (size): 10
Matrisin En Küçük Elemanı: 11
Matrisin En Büyük Elemanı: 89
Matrisin Ortalaması: 49.0
Matrisin Standart Sapması: 24.232209969377536
